---
title: Projects
---

## Education

For my undergraduate degree, I attended the University of Miami (Florida) where I earned my Bachelors in Microbiology and Immunology. I was always mystified by the microscopic world and how creatures 1000x smaller than us could cause disease. Once the SARS-CoV-2 pandemic started, I took an interest in Epidemiology as I started to appreciate the role human behavior has in infectious disease.

After graduating from Miami, I attended Case Western Reserve University to pursue a Masters in Pathology in order to continue my education and acquire research experience. I would eventually join the lab of Dr. Anna Bruchez to follow up on some of her previous findings in cellular factors that can inhibit Ebola Virus entry. I worked with Dr. Bruchez for a year until I decided to switch from the Masters in Pathology program to the university's PhD program : the Biomedical Sciences Training Program (BSTP).

Now in the BSTP, I have decided to join a close collaborator of Dr. Bruchez, Dr. Kenneth Matreyek for my doctoral training and thesis project. 

----

## Projects

During my Masters at Case Western, I investigated how a cell's endosomal trafficking system can influence filoviral infection. Since I have joined the BSTP, another student has taken over this project and we are working towards publishing some of the preliminary data. 

As a requirement in the BSTP, I have only just joined the lab that I will complete my thesis in this December and have not had enough time to decide a project for my thesis. 
