---
title: "Dashboard"
format: 
  dashboard:
    nav-buttons: [github]
    github: https://github.com/mine-cetinkaya-rundel/ld-dashboard
logo: images/logo.png
theme: [sandstone, theme/custom.scss]
fig-width: 10
fig-asp: 0.3
params:
  month: "October"
  year: "2023"
  # 2021 rates: https://www.cdc.gov/nchs/data/nvsr/nvsr72/nvsr72-01.pdf
  us_cesarean_rate: 0.321 
  us_preterm_rate:  0.1049
  threshold_diff: 0.02
editor_options: 
  chunk_output_type: console
---

```{r packages, message= F, warnings = F}
library(Epi) # twoby2
library(janitor)
library(knitr)
library(mosaic) # fav stats
library(broom) # tidy function
library(magrittr) #pipes
library(haven) # reads XPT files
library(patchwork)
library(Hmisc) # describe()
library(rstanarm)

library(tidyverse)

library(readxl)
library(scales)
library(DT)
library(gt)
```

```{r data_ingest}
body_meas = read_rds("body_raw.rds")

food_sec = read_rds("food_sec_raw.rds")

demog = read_rds("demo_raw.rds")

alc_use = read_rds("alc_use.rds")
```

```{r cleaning_data}
new = left_join(demog, body_meas, by = "seqn")

new2 = left_join(new, food_sec, by = "seqn")

new3 = left_join(new2, alc_use, by = "seqn")

reduced = new3 %>% filter(ridstatr == 2, ridageyr < 80, ridageyr > 20)

raw = reduced %>% select(seqn, fsq165, bmxht, bmxbmi, fsdhh, alq151, ridreth3)

raw$fsq165 = as.factor(raw$fsq165) %>% fct_recode("Received" = "1","Never" = "2", "NA" = "9", "NA" = "7")

raw$fsdhh = as.factor(raw$fsdhh) %>% fct_recode("none" = "1","low" = "2","medium" = "3","high" = "4")

raw$alq151 = as.factor(raw$alq151) %>% fct_recode("Yes" = "1","No" = "2", "NA" = "9", "NA" = "7")

raw$ridreth3 = as.factor(raw$ridreth3) %>% fct_recode("Mexican" = "1",
                                             "Hispanic" = "2",
                                             "White" = "3",
                                             "Black" = "4",
                                             "Asian" = "6",
                                             "Multi-Race/Other" = "7")

raw = raw %>% filter(fsq165 != "NA", alq151 != "NA", complete.cases(fsq165, bmxht, bmxbmi, fsdhh, alq151, ridreth3)) %>% droplevels() %>% tibble()
```


```{r load_data, message= F}
ld <- read_excel("data\\ld.xlsx")
```

```{r set_input}
time_period <- paste(params$month, params$year)
```

```{r data_prep}
ld <- ld |>
  mutate(
    delivery_method = str_to_sentence(delivery_method),
    term = str_to_sentence(term),
    parity = case_when(
      parity == "1"  ~ "Nulliparous",
      parity == "2"  ~ "Primiparous",
      parity == "3+" ~ "Multiparous"
    ),
    parity = fct_relevel(parity, "Nulliparous", "Primiparous", "Multiparous"),
    maternal_age = fct_relevel(maternal_age, "<20", "20-34", "35+")
  )
```

#  {.sidebar}

------------------------------------------------------------------------

The participants used in this analysis had complete data for the following variables:

|   NHANES Variable        |  Description   |
|--------------------------|----------------|
| **SEQN** |  ID            |
| **FSDHH**|  Household Food Insecurity     |
| **BMXBMI**|  BMI ($kg/m^2$)            |
| **ALQ167** | 4/5 Alcoholic Drinks Daily  |
|
------------------------------------------------------------------------

::: {.callout-note collapse="true"}
## Data Disclaimer 

This dashboard utilizes data from the 2017 - March 2020 National Health and Nutrition Examination Survey [sponsored by the CDC](https://wwwn.cdc.gov/nchs/nhanes/continuousnhanes/default.aspx?cycle=2017-2020).
:::

# All

```{r}
#| label: all-values
#| results: hide

n_participants <- nrow(raw)

p_fsdhh = raw %>%
  count(fsdhh) %>%
  mutate(p = n/sum(n)) %>%
  filter(fsdhh != "none") %>%
  mutate(t = sum(p)) %>%
  distinct(t) %>%
  pull(t)

p_alq151 = raw %>%
  count(alq151) %>%
  mutate(p = n/sum(n)) %>%
  filter(alq151 != "No") %>%
  pull(p)
p_alq151 

#p_preterm_color <- case_when(
#  between(p_preterm, params$us_preterm_rate, params$us_preterm_rate + params$threshold_diff) ~ "warning",
#  p_preterm > params$us_preterm_rate + params$threshold_diff ~ "danger",
#  .default = "light"
#  )
raw %>% tabyl(alq151, fsq165) %>% adorn_totals(where = c("row", "col"))

raw %>% count(alq151) %>%
  mutate(p =n/sum(n))
  
m1 = matrix(nrow = 2, c(586, 2246, 404, 2968))
rownames(m1) = c("Exessive Daily Drinking", "Non Excessive")
colnames(m1) = c("Uses SNAP", "Independent")
```

## Row {height="20%"}

```{r}
#| content: valuebox
#| title: "Participants"

list(
  icon = "file-medical",
  color = "#20603D",
  value = n_participants
)
```

```{r}
#| content: valuebox
#| title: "Americans with Food Insecurity"

list(
  icon = "clipboard2-pulse",
  color = "#49678D",
  value = label_percent(accuracy = 0.1)(p_fsdhh)
)
```

```{r}
#| content: valuebox
#| title: "Americans that Drink 4/5 Alcoholic Beverages Daily"

list(
  icon = "calendar-week",
  color = "#8B8C7A",
  value = label_percent(accuracy = 0.1)(p_alq151)
)
```

## Row {height="40%"}

### Column {width="40%"}

```{r}
#| title: Excessive Drinking and SNAP (Food Stamp) Usage
m1 %>% kable()
```

### Column {width="60%"}

```{r}
#| title: Food Insecurity

raw %>%
  count(fsdhh) %>%
  mutate(p = n/sum(n)) %>%
  ggplot(aes(x = fsdhh, y = p, group = 1))+
    geom_line() + 
    geom_point()+
  labs(x = "")+
  scale_y_continuous("Proportion", labels = label_percent())
```

## Row {height="40%"}

```{r}
#| title: Body Mass Index (Log Transformed) and Food Insecurity

ggplot(raw, aes(x = fsdhh, y = log(bmxbmi)))+
  geom_violin(aes(fill = fsdhh), alpha = 0.5)+
  geom_boxplot(width = 0.5, aes(fill = fsdhh), alpha = 0.75)+
  coord_flip()+
  labs(x = "", y=  "")

```

```{r}
#| title: Food Insecurity and Excessive Daily Drinks

raw %>%
  count(fsdhh, alq151) |>
  ggplot(aes(x = n, y = fct_rev(fsdhh), fill = alq151)) +
  geom_col(position = "fill", color = "white") +
  scale_fill_manual(
    values = c("#49678D", "#20603D"),
    guide = guide_legend(reverse = TRUE)
  ) +
  scale_x_continuous(labels = label_percent()) +
  labs(y = NULL, x = NULL, fill = "Excessive\nDaily\nDrinks")
```


# Statistics {orientation="columns"}

## Column {width="60%"}

```{r}
#| label: cesarean-values
#| results: hide

#p_preterm_color_c <- case_when(
#  between(p_preterm_c, params$us_preterm_rate, params$us_preterm_rate + params$threshold_diff) ~ "warning",
#  p_preterm_c > params$us_preterm_rate + params$threshold_diff ~ "danger",
#  .default = "light"
#  )
```

### Row {height="20%"}

```{r}
#| component: valuebox
#| title: "Total births"

#list(
 # icon = "file-medical",
#  color = "primary",
#  value = n_births_c
#)
```

```{r}
#| component: valuebox
#| title: "Pre-term births"

#list(
 # icon = "calendar-week",
 # color = p_preterm_color_c,
 # value = label_percent(accuracy = 0.1)(p_preterm_c)
#)
```

### Row {height="40%"}

```{r}
#| title: Maternal age

#ld_c |>
#  count(maternal_age) |>
 # mutate(p = n / sum(n)) |>
##  ggplot(aes(x = maternal_age, y = n, group = 1)) +
 # geom_line(linewidth = 2, color = "#0e263560") +
#  geom_point(size = 3, color = "#0e2635") +
#  geom_point(size = 6, color = "#0e2635", shape = "circle open") +
#  labs(x = NULL) +
#  scale_y_continuous(
 #   "Count",
 #   sec.axis = sec_axis(~ . / n_births, name = "Proportion", labels = label_percent())
#  )
```

### Row {height="40%" .tabset}

```{r}
#| title: Maternal age and parity

#ld_c |>
#  count(maternal_age, parity) |>
#  ggplot(aes(x = n, y = fct_rev(maternal_age), fill = fct_rev(parity))) +
#  geom_col(position = "fill", color = "white") +
#  scale_fill_brewer(
#    palette = "Blues",
##    guide = guide_legend(reverse = TRUE),
#    direction = -1
#  ) +
#  scale_x_continuous(labels = label_percent()) +
#  labs(y = NULL, x = NULL, fill = "Parity")
```

```{r}
#| title: Maternal age and term

#ld_c |>
#  count(maternal_age, term) |>
#  ggplot(aes(x = n, y = fct_rev(maternal_age), fill = fct_rev(term))) +
#  geom_col(position = "fill", color = "white") +
#  scale_fill_brewer(
#    palette = "Greens",
#    guide = guide_legend(reverse = TRUE),
#    direction = -1
#  ) +
##  scale_x_continuous(labels = label_percent()) +
#  labs(y = NULL, x = NULL, fill = "Term")
```

## Column {width="40%"}

```{r}
#| title: Data

#ld_c |>
#  select(-delivery_method) |>
#  arrange(patient_id) |>
#  datatable(
#    colnames = c("ID", "Maternal age", "Parity", "Term"),
 #   options = list(
 #     dom = "lrtip", 
#      paging = TRUE,
#      lengthMenu = c(5, 10, 25),
#      pageLength = 10, 
#      scrollY = TRUE
#    ),
# )
```

# Data

```{r}
raw %>%
  arrange(seqn) %>%
  select(seqn, fsdhh, fsq165, bmxbmi, bmxht, alq151) %>% 
  datatable(
    colnames = c("ID", "Household Food Insecurity","Household SNAP Usage",  "BMI", "Standing Height (cm)", "Excessive Daily Alcohol Consumption"),
    options = list(dom = 'ftp', paging = TRUE)
    )
```
