---
title: Blog
---

# December 12, 2024

While working towards my undergraduate degree, I took an interest in epidemiology and tracking human health at the population level. As an exercise, I have chosen to investigate if food insecurity in the United States could be predicted by one's habits or physical characteristics. To do this, I've used the CDC's National Health and Nutrition Examination Survey (NHANES) 2018 - March 2020 to compare the usage of the Supplemental Nutrition Assistance Program (SNAP; formerly known as Food Stamps), levels of food insecurity, excessive alcohol consumption (which has been deemed as 4 drinks for women and 5 drinks for men per day), and the participant's Body Mass Index (BMI). I have posted the analyses of the comparisons to the website under the [Dashboard Tab](https://shassbergerb.github.io/dashboard/dashboard.html#all).

To create the dashboard, I edited a Quarto template for dashboards in R that was provided by my statistics professor. 

My hypotheses for this investigation included that increasing levels of food insecurity would decrease an individuals BMI, that excessive daily alcoholic drinks would be correlated with higher levels of food insecurity and usage of the SNAP Program. My hypotheses were based on the idea that individuals who where in hardship to find stable food may use alcohol to cope with the stress or could be struggling to control addictive tendencies. Both using alcohol as a coping mechanism and an difficulty controlling an addiction correlating with food insecurity may provide insight into a systematic disservice to communities and households, leading to a slippery slope that is difficult to escape.

To investigate is SNAP usage was correlated with excessive alcohol consumption, I used a $\chi^2$ test; this test showed a significant difference between individuals that have have daily excessive alcohol intake and use food stamps compared to those that do not do either (p<0.01). The relative risk of someone who drinks 4-5 alcohol beverages a day to need to use the SNAP program was 1.37 (CI: 1.31, 1.45), indicating that it was more likely to occur than if the correlation was random.

To complete this analysis, I used $\chi^2$ tests and pairwise fisher tests to compare the excessive daily alcohol consumption with household food insecurity. The $\chi^2$ showed that there was at lease one group significantly different than the others (p<0.01). To identify which levels were different, the pairwise fisher showed that each level of food insecurity was different than each other, with the exceptions of the low and medium levels of food insecurity. This analysis shows that as food insecurity increases, there is an increase in daily excessive alcohol consumption.

Finally, to investigate if levels of food insecurity impacted the BMI of the individual, I created a linear model of each category and performed an ANOVA to identify if the mean of one group was different than the others. Due to the spread of BMIs in the data, I needed to transform the BMI with the natural log to reduce the wide tails of the data and make the data normal. The ANOVA of the transformed BMI returned a significant value (p<0.01), so I continued to delve deeper with a Tukey Honestly Significant Difference test to identify pairwise differences. Interestingly, there was a significant difference in the log of BMI for those that had no food insecurity and any other level; however, the log of BMI for any level of food insecurity (low-high) were not significantly different from each other. The log of BMI increased with any level of food insecurity compared to no food insecurity; this could be evidence that when people with food insecurity do have the opportunity to purchase food, it is "unhealthy" food (such as fast food).

Overall, my investigation of the NHANES 2018 - March 2020 data returned interesting observations. While my hypotheses were correct for alcohol consumption on SNAP usage or food insecurity level, the opposite was true for BMI in relation to food insecurity. Further steps in this analysis could include investigating the dietary data from the same data set, which I excluded for this initial analysis for simplicity sake, as well as looking for additional factors that could contribute to either excessive alcohol consumption or increased BMI, including but not limited to the activity level of participants or their reported stress levels. 